---
name: woodcutting
description: Basic Woodcutting skill support.
homepage: https://github.com/kryonic/woodcutting_plugin
author: kryonic
version: 0.0.1
git: https://github.com/kryonic/woodcutting_plugin.git